---

- name: Create ArgoCD namespace
  command: kubectl create namespace argocd
  ignore_errors: yes

- name: Deploy ArgoCD
  command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml


# -------------------------
# Vault
# -------------------------
- name: Add Vault Helm repo
  command: helm repo add hashicorp https://helm.releases.hashicorp.com

- name: Deploy Vault
  command: >
    helm upgrade --install vault
    hashicorp/vault
    --namespace vault
    --create-namespace


# -------------------------
# External Secrets
# -------------------------
- name: Add External Secrets repo
  command: helm repo add external-secrets https://charts.external-secrets.io

- name: Deploy External Secrets
  command: >
    helm upgrade --install external-secrets
    external-secrets/external-secrets
    --namespace external-secrets
    --create-namespace