- name: Setup Kubernetes cluster
  hosts: master:workers
  become: yes

  roles:
    - common
    - kubernetes

- name: Install Kubernetes addons
  hosts: master
  become: yes

  roles:
    - helm
    - ingress
#     - gitops