k8_version: "1.29.0-00"
kubeadm_extra_args: ""
helm_version: "v3.19.4"
ingress_chart_version: "4.14.3"
# pod_network_cidr: "10.244.0.0/16"
pod_network_cidr: "192.168.0.0/16"
postgres_db: "myappdb"
postgres_user: "myappuser"

rabbitmq_user: "myapp"
